### ISSUE TITLE
Implement List selector

### ISSUE THREAD

**Issue by vrcca** [vrcca/json_path_access#2]
According to this spec: https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-05.html#name-list-selector

**Comment by fcapovilla** [comment]
I've creating a pull request for this issue. I've implemented a part of the spec, but didn't have time to implement `get_and_update` for this selector.

**Comment by fcapovilla** [comment]
I managed to implement `get_and_update`. I've update my pull request.
